name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.20.1' # Replace with your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build and run app
      run: npm start
